services:
  providence:
    restart: unless-stopped
    depends_on: 
      - mysql
      - memcached
    volumes:
      - ${APACHE_LOGS_DIR:-./log}:/app/apache2/logs
      - ${CA_MEDIA_DIR:-./media}:/app/apache2/htdocs/media
    links:
      - mysql 
      - memcached

  mysql:
    restart: unless-stopped
    volumes:
      - $MYSQL_DATA:/var/lib/mysql 

  memcached:
    image: memcached:latest
    restart: unless-stopped
    environment:
      MEMCACHED_CACHE_SIZE: 128
