services:
  providence:
    depends_on: 
      - mysql
    build: .
    volumes:
      - $PWD:/app/apache2/htdocs
    ports:
      - "8080:80"
    links:
      - mysql 

  mysql:
    image: mysql:5.7
    volumes:
      - $MYSQL_DATA:/var/lib/mysql 
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword 
      MYSQL_DATABASE: ca 
      MYSQL_USER: ca_user 
      MYSQL_PASSWORD: ca_password 
